### ISSUE TITLE
Requête login

### ISSUE THREAD

**Issue by GianniGiudice** [AcLabM1/DNE-API#37]
Requête GET en envoyant deux données :

- email
- mot de passe

Retour de l'API avec les données suivantes : 

- code de retour (200 ou 403 par exemple)
- token
- role (étudiant, intervenant, tuteur)

**Comment by J-Dudek** [comment]
Route implémentée
```curl -X POST "http://localhost:8080/account/login?password=VALEUR&username=VALEUR" -H "accept: */*"```
Mergé sur la branche main
