### ISSUE TITLE
Appel API Notes

### ISSUE THREAD

**Issue by GianniGiudice** [AcLabM1/DNE-API#62]
Lorsqu'un appel est fait à l'api via une route "/mark" par exemple en envoyant les données suivantes :
-user_id

Alors l'application appelante doit pouvoir récupérer les informations suivantes :
-pour chaque promotion, avoir une liste de chaque UE pour chaque semestre et pour chaque UE avoir les matières avec les notes. (plus explicite dans le JSON ci-dessous)

Exemple de retour JSON :

```
{
   "years": [
      "2019-2020": {
         "semesters": [
            "1": {
               "UEs": [
                  "1": {
                     "name": "Development",
                     "subjects": [
                        "1": {
                           "name": "Web Development", 
                           "ECTS_nb": 5,
                           "marks": [
                              18, 14, 16, 19
                           ]
                        }, 
                        "2": {
                           "name": "C Programming", 
                           "ECTS_nb": 3, 
                           "marks": [
                              12, 14, 18, 16
                           ]
                        }
                     ]
                  }, 
                  "2": {
                     "name": "Others",
                     "subjects": [
                        "Sport": {}
                     ]
                  }
               ]
            }, 
            "2": {...}
         ]
      }
   ]
}
```

**Comment by GianniGiudice** [comment]
Si la structure demandée est trop compliquée, nous pouvons faire des appels découpés comme par exemple la simple récupération de Matières :


En appelant la route "/matieres", nous envoyons en données un "user_id".

Notre application doit alors pouvoir récupérer les informations suivantes :
-Matières du semestre en cours (en fonction de la date où l'appel a été fait)

Exemple de retour JSON :

```
{
   "matières": [
      "1": {
         "name": "Web development", 
         "id": 124
      }, 
      "2": {} 
   ]
}
```

**Comment by GianniGiudice** [comment]
**NB :** Dîtes-moi si ça vous va comme données en entrée / sortie ou si ça ne va pas. En fonction nous pourrons faire la suite (avec l'id de chaque matière récupérée, nous pourrons faire appel à une route "/notes" en envoyant un id de la matière voulue par exemple)

**Comment by PierreDarcas** [comment]
A priori on devrait pouvoir renvoyer un json correspondant à ton premier commentaires, l'agencement des données sera peut-être pas tout à fait le mêmes, mais très proche
si vous voulez avoir une idée plus précise vous pouvez regarder dans le code de l'api la déclaration des dto, ça vous donnera une idée de la façon dont ça arrivera chez vous, et de ce que contiennent les objets.
