### ISSUE TITLE
Appel API Absences

### ISSUE THREAD

**Issue by GianniGiudice** [AcLabM1/DNE-API#64]
En appelant la route "/absences/{user_id} nous envoyons en données un "user_id".

Notre application doit alors pouvoir récupérer les informations suivantes :
-Id des sessions où l'utilisateur n'a pas été présent (via votre entité AssisterSession)

Exemple de retour JSON :

```
{
   "absences": [
      "1": {
         "session_id": "1"
      }
   ]
}
```

Ensuite, en appelant la route "/absences/{user_id}/{session_id}", nous envoyons en données un "user_id" ainsi que la "session_id" du cours où l'utilisateur a été absent.

Notre application doit alors pouvoir récupérer les informations de la session (findAll sur Session)

Enfin, en appelant la route "/matiere/{matiere_id}", nous envoyons en données un "matiere_id".

Notre application doit alors pouvoir récupérer les informations de la matière (findById sur Matiere)

Nous aurons alors toutes les informations nécessaires pour afficher les absences d'un utilisateur.

**Comment by PierreDarcas** [comment]
user findById
